from django.urls import path

from . import views

urlpatterns = [
    path('',
         views.index,
         name='index'),
    path(
        'international_energy',
        views.international_energy,
        name='international_energy'
    ),
    path(
        'international_free_trade_agreements',
        views.international_free_trade_agreements,
        name='international_free_trade_agreements'
    ),
    path(
        'international_lands_for_injecting_gas',
        views.international_lands_for_injecting_gas,
        name='international_lands_for_injecting_gas'
    ),
    path(
        'international_electricity_generation_without_license',
        views.international_electricity_generation_without_license,
        name='international_electricity_generation_without_license'
    ),
    path(
        'countries_with_gas_networks',
        views.countries_with_gas_networks,
        name='countries_with_gas_networks'
    ),
    path(
        'international_energy_needs_for_abundance',
        views.international_energy_needs_for_abundance,
        name='international_energy_needs_for_abundance'
    ),
    path(
        'forecast_of_worldwide_ammonia_production',
        views.forecast_of_worldwide_ammonia_production,
        name='forecast_of_worldwide_ammonia_production'
    ),
    path(
        'forecast_of_worldwide_natural_gas_reserves',
        views.forecast_of_worldwide_natural_gas_reserves,
        name='forecast_of_worldwide_natural_gas_reserves'
    ),
    path(
        'international_real_estate_price',
        views.international_real_estate_price,
        name='international_real_estate_price'
    ),
    path(
        'international_plastic_waste',
        views.international_plastic_waste,
        name='international_plastic_waste'
    ),
    path(
        'forecast_of_worldwide_coal_reserves',
        views.forecast_of_worldwide_coal_reserves,
        name='forecast_of_worldwide_coal_reserves'
    ),
    path(
        'forcecast_of_worldwide_crude_oil_reserves',
        views.forcecast_of_worldwide_crude_oil_reserves,
        name='forcecast_of_worldwide_crude_oil_reserves'
    ),
    path(
        'forecast_of_worldwide_uranium_reserves',
        views.forecast_of_worldwide_uranium_reserves,
        name='forecast_of_worldwide_uranium_reserves'
    ),
    path(
        'worldwide_mercury_producers',
        views.worldwide_mercury_producers,
        name='worldwide_mercury_producers'
    ),
    path(
        'countries_ratified_minamata_convention',
        views.countries_ratified_minamata_convention,
        name='countries_ratified_minamata_convention'
    ),
    path(
        'les_sites_dinjection_de_biomethane_en_france_json',
        views.les_sites_dinjection_de_biomethane_en_france_json,
        name='les_sites_dinjection_de_biomethane_en_france_json'
    ),
    path(
        'communes_desservies_en_gaz_json',
        views.communes_desservies_en_gaz_json,
        name='communes_desservies_en_gaz_json'
    ),
    path(
        'cadastre_77304_parcelles_json',
        views.cadastre_77304_parcelles_json,
        name='cadastre_77304_parcelles_json'
    ),
    path(
        'cadastre_77304_batiments_json',
        views.cadastre_77304_batiments_json,
        name='cadastre_77304_batiments_json'
    ),
    path('cadastre_77015_parcelles_json', views.cadastre_77015_parcelles_json, name='cadastre_77015_parcelles_json'),
    path('cadastre_77015_batiments_json', views.cadastre_77015_batiments_json, name='cadastre_77015_batiments_json'),
    path('cadastre_77356_parcelles_json', views.cadastre_77356_parcelles_json, name='cadastre_77356_parcelles_json'),
    path('cadastre_77356_batiments_json', views.cadastre_77356_batiments_json, name='cadastre_77356_batiments_json'),
    path('cadastre_77452_parcelles_json', views.cadastre_77452_parcelles_json, name='cadastre_77452_parcelles_json'),
    path('cadastre_77452_batiments_json', views.cadastre_77452_batiments_json, name='cadastre_77452_batiments_json'),
    path('cadastre_77532_parcelles_json', views.cadastre_77532_parcelles_json, name='cadastre_77532_parcelles_json'),
    path('cadastre_77532_batiments_json', views.cadastre_77532_batiments_json, name='cadastre_77532_batiments_json'),
    path('cadastre_78264_parcelles_json', views.cadastre_78264_parcelles_json, name='cadastre_78264_parcelles_json'),
    path('cadastre_78264_batiments_json', views.cadastre_78264_batiments_json, name='cadastre_78264_batiments_json'),
    path('cadastre_78606_parcelles_json', views.cadastre_78606_parcelles_json, name='cadastre_78606_parcelles_json'),
    path('cadastre_78606_batiments_json', views.cadastre_78606_batiments_json, name='cadastre_78606_batiments_json'),
    path('cadastre_91075_parcelles_json', views.cadastre_91075_parcelles_json, name='cadastre_91075_parcelles_json'),
    path('cadastre_91075_batiments_json', views.cadastre_91075_batiments_json, name='cadastre_91075_batiments_json'),
    path('cadastre_91145_parcelles_json', views.cadastre_91145_parcelles_json, name='cadastre_91145_parcelles_json'),
    path('cadastre_91145_batiments_json', views.cadastre_91145_batiments_json, name='cadastre_91145_batiments_json'),
    path('cadastre_95141_parcelles_json', views.cadastre_95141_parcelles_json, name='cadastre_95141_parcelles_json'),
    path('cadastre_95141_batiments_json', views.cadastre_95141_batiments_json, name='cadastre_95141_batiments_json'),
    path('cadastre_95144_parcelles_json', views.cadastre_95144_parcelles_json, name='cadastre_95144_parcelles_json'),
    path('cadastre_95144_batiments_json', views.cadastre_95144_batiments_json, name='cadastre_95144_batiments_json'),
    path('cadastre_95214_parcelles_json', views.cadastre_95214_parcelles_json, name='cadastre_95214_parcelles_json'),
    path('cadastre_95214_batiments_json', views.cadastre_95214_batiments_json, name='cadastre_95214_batiments_json'),
    path('cadastre_95387_parcelles_json', views.cadastre_95387_parcelles_json, name='cadastre_95387_parcelles_json'),
    path('cadastre_95387_batiments_json', views.cadastre_95387_batiments_json, name='cadastre_95387_batiments_json'),
    path('cadastre_95492_parcelles_json', views.cadastre_95492_parcelles_json, name='cadastre_95492_parcelles_json'),
    path('cadastre_95492_batiments_json', views.cadastre_95492_batiments_json, name='cadastre_95492_batiments_json'),
    path('cadastre_95611_parcelles_json', views.cadastre_95611_parcelles_json, name='cadastre_95611_parcelles_json'),
    path('cadastre_95611_batiments_json', views.cadastre_95611_batiments_json, name='cadastre_95611_batiments_json'),
    path('cadastre_95633_parcelles_json', views.cadastre_95633_parcelles_json, name='cadastre_95633_parcelles_json'),
    path('cadastre_95633_batiments_json', views.cadastre_95633_batiments_json, name='cadastre_95633_batiments_json'),
    path('cadastre_77010_parcelles_json', views.cadastre_77010_parcelles_json, name='cadastre_77010_parcelles_json'),
    path('cadastre_77010_batiments_json', views.cadastre_77010_batiments_json, name='cadastre_77010_batiments_json'),
    path('cadastre_77044_parcelles_json', views.cadastre_77044_parcelles_json, name='cadastre_77044_parcelles_json'),
    path('cadastre_77044_batiments_json', views.cadastre_77044_batiments_json, name='cadastre_77044_batiments_json'),
    path('cadastre_77071_parcelles_json', views.cadastre_77071_parcelles_json, name='cadastre_77071_parcelles_json'),
    path('cadastre_77071_batiments_json', views.cadastre_77071_batiments_json, name='cadastre_77071_batiments_json'),
    path('cadastre_77077_parcelles_json', views.cadastre_77077_parcelles_json, name='cadastre_77077_parcelles_json'),
    path('cadastre_77077_batiments_json', views.cadastre_77077_batiments_json, name='cadastre_77077_batiments_json'),
    path('cadastre_77089_parcelles_json', views.cadastre_77089_parcelles_json, name='cadastre_77089_parcelles_json'),
    path('cadastre_77089_batiments_json', views.cadastre_77089_batiments_json, name='cadastre_77089_batiments_json'),
    path('cadastre_77162_parcelles_json', views.cadastre_77162_parcelles_json, name='cadastre_77162_parcelles_json'),
    path('cadastre_77162_batiments_json', views.cadastre_77162_batiments_json, name='cadastre_77162_batiments_json'),
    path('cadastre_77172_parcelles_json', views.cadastre_77172_parcelles_json, name='cadastre_77172_parcelles_json'),
    path('cadastre_77172_batiments_json', views.cadastre_77172_batiments_json, name='cadastre_77172_batiments_json'),
    path('cadastre_77188_parcelles_json', views.cadastre_77188_parcelles_json, name='cadastre_77188_parcelles_json'),
    path('cadastre_77188_batiments_json', views.cadastre_77188_batiments_json, name='cadastre_77188_batiments_json'),
    path('cadastre_77196_parcelles_json', views.cadastre_77196_parcelles_json, name='cadastre_77196_parcelles_json'),
    path('cadastre_77196_batiments_json', views.cadastre_77196_batiments_json, name='cadastre_77196_batiments_json'),
    path('cadastre_77232_parcelles_json', views.cadastre_77232_parcelles_json, name='cadastre_77232_parcelles_json'),
    path('cadastre_77232_batiments_json', views.cadastre_77232_batiments_json, name='cadastre_77232_batiments_json'),
    path('cadastre_77283_parcelles_json', views.cadastre_77283_parcelles_json, name='cadastre_77283_parcelles_json'),
    path('cadastre_77283_batiments_json', views.cadastre_77283_batiments_json, name='cadastre_77283_batiments_json'),
    path('cadastre_77291_parcelles_json', views.cadastre_77291_parcelles_json, name='cadastre_77291_parcelles_json'),
    path('cadastre_77291_batiments_json', views.cadastre_77291_batiments_json, name='cadastre_77291_batiments_json'),
    path('cadastre_77293_parcelles_json', views.cadastre_77293_parcelles_json, name='cadastre_77293_parcelles_json'),
    path('cadastre_77293_batiments_json', views.cadastre_77293_batiments_json, name='cadastre_77293_batiments_json'),
    path('cadastre_77354_parcelles_json', views.cadastre_77354_parcelles_json, name='cadastre_77354_parcelles_json'),
    path('cadastre_77354_batiments_json', views.cadastre_77354_batiments_json, name='cadastre_77354_batiments_json'),
    path('cadastre_77406_parcelles_json', views.cadastre_77406_parcelles_json, name='cadastre_77406_parcelles_json'),
    path('cadastre_77406_batiments_json', views.cadastre_77406_batiments_json, name='cadastre_77406_batiments_json'),
    path('cadastre_77432_parcelles_json', views.cadastre_77432_parcelles_json, name='cadastre_77432_parcelles_json'),
    path('cadastre_77432_batiments_json', views.cadastre_77432_batiments_json, name='cadastre_77432_batiments_json'),
    path('cadastre_77480_parcelles_json', views.cadastre_77480_parcelles_json, name='cadastre_77480_parcelles_json'),
    path('cadastre_77480_batiments_json', views.cadastre_77480_batiments_json, name='cadastre_77480_batiments_json'),
    path('cadastre_77534_parcelles_json', views.cadastre_77534_parcelles_json, name='cadastre_77534_parcelles_json'),
    path('cadastre_77534_batiments_json', views.cadastre_77534_batiments_json, name='cadastre_77534_batiments_json'),
    path('cadastre_78020_parcelles_json', views.cadastre_78020_parcelles_json, name='cadastre_78020_parcelles_json'),
    path('cadastre_78020_batiments_json', views.cadastre_78020_batiments_json, name='cadastre_78020_batiments_json'),
    path('cadastre_78034_parcelles_json', views.cadastre_78034_parcelles_json, name='cadastre_78034_parcelles_json'),
    path('cadastre_78034_batiments_json', views.cadastre_78034_batiments_json, name='cadastre_78034_batiments_json'),
    path('cadastre_78246_parcelles_json', views.cadastre_78246_parcelles_json, name='cadastre_78246_parcelles_json'),
    path('cadastre_78246_batiments_json', views.cadastre_78246_batiments_json, name='cadastre_78246_batiments_json'),
    path('cadastre_78289_parcelles_json', views.cadastre_78289_parcelles_json, name='cadastre_78289_parcelles_json'),
    path('cadastre_78289_batiments_json', views.cadastre_78289_batiments_json, name='cadastre_78289_batiments_json'),
    path('cadastre_78307_parcelles_json', views.cadastre_78307_parcelles_json, name='cadastre_78307_parcelles_json'),
    path('cadastre_78307_batiments_json', views.cadastre_78307_batiments_json, name='cadastre_78307_batiments_json'),
    path('cadastre_78381_parcelles_json', views.cadastre_78381_parcelles_json, name='cadastre_78381_parcelles_json'),
    path('cadastre_78381_batiments_json', views.cadastre_78381_batiments_json, name='cadastre_78381_batiments_json'),
    path('cadastre_78410_parcelles_json', views.cadastre_78410_parcelles_json, name='cadastre_78410_parcelles_json'),
    path('cadastre_78410_batiments_json', views.cadastre_78410_batiments_json, name='cadastre_78410_batiments_json'),
    path('cadastre_78443_parcelles_json', views.cadastre_78443_parcelles_json, name='cadastre_78443_parcelles_json'),
    path('cadastre_78443_batiments_json', views.cadastre_78443_batiments_json, name='cadastre_78443_batiments_json'),
    path('cadastre_78464_parcelles_json', views.cadastre_78464_parcelles_json, name='cadastre_78464_parcelles_json'),
    path('cadastre_78464_batiments_json', views.cadastre_78464_batiments_json, name='cadastre_78464_batiments_json'),
    path('cadastre_78497_parcelles_json', views.cadastre_78497_parcelles_json, name='cadastre_78497_parcelles_json'),
    path('cadastre_78497_batiments_json', views.cadastre_78497_batiments_json, name='cadastre_78497_batiments_json'),
    path('cadastre_78516_parcelles_json', views.cadastre_78516_parcelles_json, name='cadastre_78516_parcelles_json'),
    path('cadastre_78516_batiments_json', views.cadastre_78516_batiments_json, name='cadastre_78516_batiments_json'),
    path('cadastre_78557_parcelles_json', views.cadastre_78557_parcelles_json, name='cadastre_78557_parcelles_json'),
    path('cadastre_78557_batiments_json', views.cadastre_78557_batiments_json, name='cadastre_78557_batiments_json'),
    path('cadastre_78569_parcelles_json', views.cadastre_78569_parcelles_json, name='cadastre_78569_parcelles_json'),
    path('cadastre_78569_batiments_json', views.cadastre_78569_batiments_json, name='cadastre_78569_batiments_json'),
    path('cadastre_78588_parcelles_json', views.cadastre_78588_parcelles_json, name='cadastre_78588_parcelles_json'),
    path('cadastre_78588_batiments_json', views.cadastre_78588_batiments_json, name='cadastre_78588_batiments_json'),
    path('cadastre_78623_parcelles_json', views.cadastre_78623_parcelles_json, name='cadastre_78623_parcelles_json'),
    path('cadastre_78623_batiments_json', views.cadastre_78623_batiments_json, name='cadastre_78623_batiments_json'),
    path('cadastre_91041_parcelles_json', views.cadastre_91041_parcelles_json, name='cadastre_91041_parcelles_json'),
    path('cadastre_91041_batiments_json', views.cadastre_91041_batiments_json, name='cadastre_91041_batiments_json'),
    path('cadastre_91293_parcelles_json', views.cadastre_91293_parcelles_json, name='cadastre_91293_parcelles_json'),
    path('cadastre_91293_batiments_json', views.cadastre_91293_batiments_json, name='cadastre_91293_batiments_json'),
    path('cadastre_91469_parcelles_json', views.cadastre_91469_parcelles_json, name='cadastre_91469_parcelles_json'),
    path('cadastre_91469_batiments_json', views.cadastre_91469_batiments_json, name='cadastre_91469_batiments_json'),
    path('cadastre_91546_parcelles_json', views.cadastre_91546_parcelles_json, name='cadastre_91546_parcelles_json'),
    path('cadastre_91546_batiments_json', views.cadastre_91546_batiments_json, name='cadastre_91546_batiments_json'),
    path('cadastre_91639_parcelles_json', views.cadastre_91639_parcelles_json, name='cadastre_91639_parcelles_json'),
    path('cadastre_91639_batiments_json', views.cadastre_91639_batiments_json, name='cadastre_91639_batiments_json'),
    path('cadastre_95008_parcelles_json', views.cadastre_95008_parcelles_json, name='cadastre_95008_parcelles_json'),
    path('cadastre_95008_batiments_json', views.cadastre_95008_batiments_json, name='cadastre_95008_batiments_json'),
    path('cadastre_95101_parcelles_json', views.cadastre_95101_parcelles_json, name='cadastre_95101_parcelles_json'),
    path('cadastre_95101_batiments_json', views.cadastre_95101_batiments_json, name='cadastre_95101_batiments_json'),
    path('cadastre_95395_parcelles_json', views.cadastre_95395_parcelles_json, name='cadastre_95395_parcelles_json'),
    path('cadastre_95395_batiments_json', views.cadastre_95395_batiments_json, name='cadastre_95395_batiments_json'),
    path('cadastre_95541_parcelles_json', views.cadastre_95541_parcelles_json, name='cadastre_95541_parcelles_json'),
    path('cadastre_95541_batiments_json', views.cadastre_95541_batiments_json, name='cadastre_95541_batiments_json'),
    path('cadastre_95554_parcelles_json', views.cadastre_95554_parcelles_json, name='cadastre_95554_parcelles_json'),
    path('cadastre_95554_batiments_json',
         views.cadastre_95554_batiments_json,
         name='cadastre_95554_batiments_json'),
    path('sale_of_databases_of_mathematics',
         views.sale_of_databases_of_mathematics,
         name='sale_of_databases_of_mathematics'),
    path('sale_of_database_of_mathematics_about_complex_variables',
         views.sale_of_database_of_mathematics_about_complex_variables,
         name='sale_of_database_of_mathematics_about_complex_variables'),
    path('sale_of_database_of_mathematics_about_quantum_groups',
         views.sale_of_database_of_mathematics_about_quantum_groups,
         name='sale_of_database_of_mathematics_about_quantum_groups'),
    path('mendeleev_table',
         views.mendeleev_table,
         name='mendeleev_table'),
    path('sale_of_database_of_mathematics_about_non_commutative_algebra',
         views.sale_of_database_of_mathematics_about_non_commutative_algebra,
         name='sale_of_database_of_mathematics_about_non_commutative_algebra'),
    path('sale_of_database_of_mathematics_about_factorization_divisibility',
         views.sale_of_database_of_mathematics_about_factorization_divisibility,
         name='sale_of_database_of_mathematics_about_factorization_divisibility'),
    path('sale_of_database_of_mathematics_about_matrix',
         views.sale_of_database_of_mathematics_about_matrix,
         name='sale_of_database_of_mathematics_about_matrix'),
    path('fundamental_research_of_inventions',
         views.fundamental_research_of_inventions,
         name='fundamental_research_of_inventions'),
    path('fundamental_research_of_patent_us_4661747',
         views.fundamental_research_of_patent_us_4661747,
         name='fundamental_research_of_patent_us_4661747'),
]
